### PR TITLE
[WIP] Fuse Interface

### PR DESCRIPTION
**Pull request by quasiben**
PR adds a fuse interface using the `hdfs3` lib

- [x] ls
- [x] copy
- [ ] move
- [x] create
- [x] delete

## Setup
- install fuse/libfuse
 - apt-get install libfuse2 fuse
 - yum install fuse fuse-libs.x86_64
- mkdir hdfs_mnt
- pip install fusepy
- python hdfsfuse.py / hdfs_mnt/

```
ubuntu@ip-172-31-54-49:~$ ll /home/ubuntu/hdfs_mnt/
total 4
drwxr-xr-x  0 hdfs   hadoop 4096 Feb  5 22:13 ./
drwxr-xr-x 15 ubuntu ubuntu 4096 Feb  9 02:14 ../
drwxrwxrwt  0 hdfs   hadoop 4096 Feb  2 14:23 tmp/
drwxr-xr-t  0 hdfs   hadoop 4096 Feb  2 05:12 user/
drwxr-xr-x  0 hdfs   hadoop 4096 Feb  2 05:12 var/
```

### CODE REVIEW

**Comment by martindurant** [comment]
I am getting `RuntimeError: 1` - was there any additional setup aside from apt-get for fuse and pip install fusepy?

**Comment by quasiben** [comment]
you will also need `libfuse`

- yum install fuse-libs.x86_64
- apt-get install libfuse2

**Comment by quasiben** [comment]
You may also need to change the `HDFileSystem()` constructor to use the correct host:ip

**Comment by martindurant** [comment]
To work in docker, required ` --cap-add SYS_ADMIN --device /dev/fuse ` on the docker run command.
Not yet complete, and no tests (it's bash stuff), but I encourage people to play. Move may already work, and append should not be difficult.

**Pull request closed without merging**
