### PR TITLE
Add versioneer

### PR DESCRIPTION
**Pull request by jcrist**
Allows checking versions on non-release builds.

### CODE REVIEW

**Comment by martindurant** [comment]
Is this really necessary? Versioneer is pretty annoying in my experience, with rogue `_version.py` files around and such.

**Comment by jcrist** [comment]
Rogue `_version.py` files?

I've had no issues with versioneer, and in my experience it helps when integrating disparate versions from different projects, especially when testing functionality that only exists on master branches. In this specific case I need it to check if the hdfs3 version is after the latest release. Since we use it in most other dask projects I see no harm in including it here.

**Comment by jcrist** [comment]
Failures are due to need for https://github.com/dask/dask/pull/2894.

**Comment by jcrist** [comment]
Everything is synced up now, tests pass. Merging.

**Pull request merged**
