### PR TITLE
Add informative error message when missing libhdfs3

### PR DESCRIPTION
**Pull request by mrocklin**
cc @bolkedebruin @jettify

### CODE REVIEW

**Comment by bolkedebruin** [comment]
On https://github.com/PivotalRD/libhdfs3/releases it shows how to install on rpm based systems. 

maybe add it or just include the link?

**Comment by koverholt** [comment]
I would prefer if we link to the libhdfs3 documentation rather than include specific apt-get commands in the error message (note that those are only valid for Ubuntu 14.04).

Alternatively, we could add these links to our own docs installation page and link to that from this error message.

**Comment by jettify** [comment]
I am happy with any approach, but linking to `hdfs3` docs with various instructions looks more clean to me.

**Comment by mrocklin** [comment]
Agreed.  I'll write something up and add it here in a while.

**Comment by mrocklin** [comment]
Updated

**Comment by koverholt** [comment]
:+1: LGTM.

**Pull request merged**
