### PR TITLE
Check for libhdfs3 in ../lib

### PR DESCRIPTION
**Pull request by mrocklin**
Fixes https://github.com/conda-forge/hdfs3-feedstock/issues/4

### CODE REVIEW

**Comment by mrocklin** [comment]
Merging soon if no comments

**Comment by koverholt** [comment]
I think that we should also return the original exception to the user here. A couple of cases were obscuring other library issues such as missing `libgcrypt` or other missing libraries during this check: https://github.com/dask/hdfs3/issues/97

**Comment by mrocklin** [comment]
Can do.  Should this still go in with the change?

**Comment by koverholt** [comment]
I'm not 100% sure, the existing check seems to be doing it's job. Is there a case where this PR would fix something a user was running into?

**Comment by mrocklin** [comment]
I no longer recall my exact situation, but libraries found in the anaconda/lib directory were definitely not being picked up by the operating system.  For example bash calls like `locate libhdfs3` were coming up empty.

**Comment by martindurant** [comment]
What is the status of this PR, is it useful?

**Comment by mrocklin** [comment]
My understanding is that it is a convention to put shared libraries within the directory pointed to here, but that this isn't enforced in any way by Conda, so shared libraries there may not be reliably found.  I suspect that this is not necessary in systems that reliably set the load library path but may be useful in more casual cases.  I'm generally in favor of putting it in, but I don't have the sysops experience to say so definitively.

**Comment by martindurant** [comment]
OK; well I see no harm from looking in this extra place, even if it's only semi-conventional. Merging.

**Pull request merged**
