### PR TITLE
add closed, seekable, writable, readable

### PR DESCRIPTION
**Pull request by mrocklin**

### CODE REVIEW

**Comment by martindurant** [comment]
Looks simple and worthwhile to me

**Comment by mrocklin** [comment]
I updated our travis settings to test PRs coming from other forks.

**Comment by martindurant** [comment]
I am seeing ci/anaconda failing immediately on my PR and two Travis processes.

**Comment by mrocklin** [comment]
Moving discussion to https://github.com/dask/hdfs3/pull/80

**Pull request merged**
