### PR TITLE
Conf rework

### PR DESCRIPTION
**Pull request by martindurant**
A more sensible scheme for auto-guessing configuration and overriding where necessary.

This still requires docs and tests; posting now for any comments.

### CODE REVIEW

**Comment by martindurant** [comment]
Notice that commits history looks a bit ... odd. Will clean at merge time.

**Comment by martindurant** [comment]
@quasiben : I am trying to make the way to provide configuration parameters to hdfs3 and knit much more straight forwards. In fact, I am considering having knit depend on hdfs3.

What do you think of the scheme here? It needs docs, but the idea is to take values from
- xml files in locations given by environment variables, or typical locations, or local dir (in that order); also sets LIBHDFS3_CONF if anything was found, before the .so is imported. If no file was found anywhere, you get `{'host': 'localhost', 'port': 8020}`.
- xml file explicitly passed to `hdfs3.conf.hdfs_conf()`
- direct editing of `hdfs3.conf.conf`, which is the dict made automatically
- dict of values passed to the constructor (looks like produced by `hdfs3.conf.conf_to_dict()`)
- key/values passed in the constructor to override specific values (`port=None`)

If `autoconf=False`, the first three steps are skipped. In this case, if you don't pass at least `host=`, you get an error, not even the default `localhost`.

**Comment by quasiben** [comment]
This looks really good.  I do have one question, when would a user edit `hdfs3.conf.conf` vs configuring with the constructor?

Also, I can see why you would want to share this bit of config code with knit but I would advise against it unless you see knit doing more things with hdfs3 on the python side rather than raw hdfs calls on the jvm side

**Comment by martindurant** [comment]
> edit hdfs3.conf.conf vs configuring with the constructor

Perhaps so that it can be done once in a setup script and then it persists in the global without having to send the parameter again? It could be a possibility that doesn't get mentioned in the doc if you think it's confusing.

Another thought on this: the import of the .so could be delayed until a HDFileSystem tries to connect, giving more opportunity to do any editing, and allowing import of hdfs3 without the risks of forking.

Question: some users probably do HDFileSystem(host, port) without keywords; do you think I should accept a 2-element `*args` to account for the possibility?

On hdfs3 in knit: I already reference it [here](https://github.com/dask/knit/blob/master/knit/core.py#L504-L538) to only upload environments if required. I am thinking that hdfs3's ability to generate hdfs delegation tokens may be the best way to get around permission issues, although the scala client can presumably do that too (if it somehow gets ticket caches etc., from the default config files).

**Pull request merged**
