### PR TITLE
Add putiter method to write iterators of bytes to HDFS

### PR DESCRIPTION
**Pull request by cpcloud**

### CODE REVIEW

**Comment by mrocklin** [comment]
I'm curious, what is the motivation/application here?

**Comment by cpcloud** [comment]
Making ibis work with HDFileSystem.

**Comment by cpcloud** [comment]
The current `put` implementation in `hdfs3` requires a local file which ibis has already placed into an object that implements the file protocol, I'd like to avoid writing that to local disk again.

**Comment by mrocklin** [comment]
I guess the alternative here would be to open the hdfs3 file and write directly with a for loop each time.  This would be somewhat inconvenient, but, given that the function is only three lines long, presumably possible.

My guess is that the counter-argument to this change would be that we wouldn't be adding another term to the API, which we might want to keep somewhat minimal for maintenance and consistency reasons.  In particular, if we add it here then we should probably also add it to s3fs, adlfs, and gcsfs.  Of course, if that encourages other tools like Ibis to adopt those tools then that's a very small price to pay.

More broadly, I like the idea of encouraging integration between "the stuff happening with Dask" and "the stuff happening with ibis/arrow/etc.."  Are there other topics or interfaces that we should try to agree upon and write down concretely?

In any event, given that @martindurant mostly maintains these libraries he should probably determine things.

**Comment by cpcloud** [comment]
Hm, good point. No need to add a new method.

I think the first point of integration is probably agreeing on a filesystem interface. [The one that ibis implements using webhdfs](https://github.com/cloudera/ibis/blob/master/ibis/filesystems.py#L246) and `HDFileSystem`'s mostly overlap in a compatible way, modulo some keyword arguments and argument ordering. It'd be great if we could make `HDFileSystem` the preferred interface. WebHDFS is extremely difficult to debug.

**Comment by martindurant** [comment]
Additional to the comments above, what are your thoughts on the corresponding get method?
In my mind, an operation like this would indeed have been done via the open method, but I had not conceived of a bytes operator as a thing.

**Comment by mrocklin** [comment]
I thought that PyArrow offered an HDFS connection through libhdfs.  Is that an option?

**Comment by cpcloud** [comment]
It does have that, but I'm not ready to introduce that kind of dependency into ibis yet.

**Comment by mrocklin** [comment]
FYI LibHDFS3 may have issues of its own.  See https://github.com/dask/dask/issues/1880 

It may be interesting to explore if there are any opportunities to collaborate on remote byte management.  The [dask/bytes/](https://github.com/dask/dask/tree/master/dask/bytes) module may be of more general interest.

**Comment by cpcloud** [comment]
Interesting, thanks for the heads up!

**Pull request closed without merging**
